name: score-every-15
on:
  schedule:
    - cron: '*/15 7-17 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call server to update scores
        run: |
          curl --request POST \
          --url '${{ secrets.CLIENT_URL }}' \
          --header 'authorization: ${{ secrets.SCORE_PREDICTIONS_PASSWORD }}' \
          --header 'accept-language: es'